### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by MilenTecle** [MilenTecle/Inventory-Manager#1]
As a **user**, I want to **create an account** so that **I can start managing my inventories**.

### Tasks

- [ ]  Create a user registration page.

- [ ] Include form fields for username, email and password.

- [ ] Redirect the user to the login page upon successful registration

**Comment by VidyaYadavv1519** [comment]
hiii, i want to do this issue can you please assign me this issue ??
