### ISSUE TITLE
User Managment

### ISSUE THREAD

**Issue by MilenTecle** [MilenTecle/Inventory-Manager#10]
As an **admin** I want **to view a list of all registered users** so that **I can view and modify user details, and deactivate or delete user accounts if necessary**.

### Tasks

- [ ] Create a view to display a list o fall registered users.
- [ ] Implement functionality to delete or deactivate user accounts.
- [ ] Implement functionality to edit user details.
