### ISSUE TITLE
Create a new inventory

### ISSUE THREAD

**Issue by MilenTecle** [MilenTecle/Inventory-Manager#3]
As a **user**, I want to **create an inventory list and add its items in one step,** so that **I can organize my belongings efficiently**.

### Tasks

- [ ] Create a form so the user can add the inventory name followed by the list items.
- [ ] Add functionality to edit, delete and save the items.
- [ ] The created inventory should be associated with the logged-in user.

**Comment by VidyaYadavv1519** [comment]
hello, i want to do this issue,
can you please assign me ??

**Comment by MilenTecle** [comment]
@VidyaYadavv1519 - this is for my Code Institute project so I need to resolve the issues on my own :)
