### ISSUE TITLE
Share Inventory

### ISSUE THREAD

**Issue by MilenTecle** [MilenTecle/Inventory-Manager#5]
As a **user,** I want to **share my inventory with others using the generated QR code** so that **I can provide a visual and efficient view of the contents of my Inventory to others**.

### Tasks

- [ ] Implement a share functionality on the inventory page.
- [ ] Allow the user to choose the sharing method via email, social media etc.
- [ ] Include the QR code image in the sharing message.
- [ ] Provide clear instructions for non-users to view the shared inventory.
