### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by MilenTecle** [MilenTecle/Inventory-Manager#6]
As a **site user** I can **navigate easily through the site due to a responsive navbar** so that **I understand where to go and it is always visible to me**.

### Tasks

- [ ] Use Bootstrap to implement  a responsive navigation bar
- [ ] Implement hamburger dropdown on smaller screens
- [ ] Add logo that takes user back to home page.
