### ISSUE TITLE
Social media links

### ISSUE THREAD

**Issue by MilenTecle** [MilenTecle/Inventory-Manager#7]
As a **user** I want**to be able to click on the social media links** so that **I can explore the work of the developer and see the developers profile**.

### Tasks

- [ ] Add LinkedIn and Github icons to the Footer.

- [ ] Link the social media icons to the profiles.

- [ ] Make sure the links opens in new window.
