### ISSUE TITLE
Manage Inventory

### ISSUE THREAD

**Issue by MilenTecle** [MilenTecle/Inventory-Manager#9]
As an **admin** I want **to view a list of all inventory items** so that **I can edit, delete or add items**.

### Tasks

- [ ] Create a view to display a list of all inventory items.

- [ ] Implement a form to add new items to the inventory.

- [ ] Implement edit and delete functionality.
